force-app/main/default/objects/Opportunity/fields/Policy__c.field-meta.xml
<CustomField>
    <fullName>Policy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Policy</label>
    <referenceTo>Policy__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referral_Friend_Name__c.field-meta.xml
<CustomField>
    <fullName>Referral_Friend_Name__c</fullName>
    <label>Referral Friend Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referred_By_Email__c.field-meta.xml
<CustomField>
    <fullName>Referred_By_Email__c</fullName>
    <label>Referral Friend Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Source_of_Leads__c</fullName>
    <description>What is the source of the Lead?</description>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vex_Voucher_Status__c.field-meta.xml
<CustomField>
    <fullName>Vex_Voucher_Status__c</fullName>
    <description>Voucher statuses permitted for VEX voucher processing.</description>
    <label>Vex Voucher Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VEX RAF Requested</fullName>
            </value>
            <value>
                <fullName>VEX RAF Higher Approved</fullName>
                <label>VEX RAF Approved</label>
            </value>
            <value>
                <fullName>VEX RAF Sent</fullName>
            </value>
            <value>
                <fullName>VEX No Voucher</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Win_Back_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Win_Back_Opportunity__c</fullName>
    <description>This field is used to indicate whether an Opportunity of the subtype &apos;Win-Back&apos; should be created (via Scheduled automation)</description>
    <label>Win-Back Opportunity</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <label>Policy</label>
    <nameField>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <description>The type of business this policy represents (New Business or Renewal).</description>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NewBusiness</fullName>
                <label>New Business</label>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>MTA</fullName>
            </value>
            <value>
                <fullName>DetailChange</fullName>
                <label>Detail Change</label>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>SelfRenewal</fullName>
                <label>Manual Renewal</label>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>RenewalLapse</fullName>
                <label>Renewal Lapse</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Expiry_Date_time__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date_time__c</fullName>
    <label>Expiry Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/From_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>From_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This links to the won Opportunity which this Policy was created from.</description>
    <label>From Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Inception_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Inception_Date_Time__c</fullName>
    <label>Inception Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Issue_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Issue_Date_Time__c</fullName>
    <description>The date the policy was issued/written. Essentially the date is was purchased.</description>
    <label>Issue Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The current status of the policy.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Default_Client_System__c.field-meta.xml
<CustomField>
    <fullName>Default_Client_System__c</fullName>
    <label>Default Client System</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Purchase_With_Other__c.field-meta.xml
<CustomField>
    <fullName>Purchase_With_Other__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Purchase With Other</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/VexTestDataFactory.cls
@isTest
public class VexTestDataFactory
{

    
public static void createVexData(Integer numAccts, Integer numOppsPerAcct, Boolean policyRequired) 
{
    List<Account> 		CustomerAccts 	= new List<Account>();
    List<Opportunity> 	CustomerOpps 	= new List<Opportunity>();
    List<Product2> 		TestProducts 	= new List<Product2>();
    List<Policy__c> 	TestPolicies 	= new List<Policy__c>();
    List<String>		VexStatuses		= new List<String>();
    
   	//VexStatuses.add('VEX RIS Lower Approved');
    VexStatuses.add('VEX RAF Higher Approved');
   	VexStatuses.add('VEX RAF Lower Approved');
   	//VexStatuses.add('VEX RIS Higher Approved');
    

	Schema.DescribeFieldResult fieldResult = Opportunity.Win_Back_Opportunity__c.getDescribe();
	List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();

	for (Schema.PicklistEntry entry : picklistValues) {
		System.debug(entry.getLabel() + ' : ' + entry.getValue());
	}
	Schema.PicklistEntry entry = picklistValues[0];
	System.debug('entry.getValue = ' + entry.getValue());
    
    Account 	test_partner;
    Account 	test_customer;
    Opportunity	test_opp;
    Product2 	test_product;
    Policy__c 	test_policy;
    DateTime 	policy_start = DateTime.now().addYears(-1).addDays(-1);
    
    
    for(Integer i=1;i<numAccts+1;i++) 
    {
        test_customer = new Account(
        FirstName = 'Vex Test',
        LastName = 'Customer ' + i,
        RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND Name = 'Customer Accounts' LIMIT 1].Id,
        PersonEmail = 'testcustomer'+i+'@example.com',
        Phone = '07777666666',
        Business_Name__c = 'Test Inc' +i,
        OwnerId = UserInfo.getUserId()
        );
        CustomerAccts.add(test_customer);
    }
    insert CustomerAccts;
    
    for(Integer i=1;i<numAccts+1;i++) 
    {
        test_product = new Product2
            (
             Name = 'Test Vex PI Product '+i,
             ProductCode = 'PI',
             IsActive = true,
             Description = 'Vex Test PI Product',
             Purchase_With_Other__c = false,
             Default_Client_System__c = 'KCI'
        );
        TestProducts.add(test_product);
    }
    insert TestProducts;


    
    for(Integer i=1;i<numAccts+1;i++) 
    {
        for (Integer j=1;j<numOppsPerAcct+1;j++) 
        {
            test_opp = new Opportunity(
                Name = 'KCI: New Business - Vex TEST/'+i+'/'+j,
                RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Opportunity' AND Name = 'New Business Opportunity' LIMIT 1].Id,
                CloseDate = Date.today().addYears(-1).addDays(-1),
                StageName = 'Prospecting',
                Type = 'New Business',
                Source_of_Leads__c = 'RAF',
                Win_Back_Opportunity__c = 'No',
                AccountId = CustomerAccts[i-1].Id,
        		Referred_By_Email__c = 'testreferred'+i+'@example.com',
                Referral_Friend_Name__c = 'Vex Test Refer '+i,
                Vex_Voucher_Status__c = VexStatuses[math.mod(i,VexStatuses.size())],
                OwnerId = UserInfo.getUserId()
            );
            CustomerOpps.add(test_opp);               
        }
    }
    insert CustomerOpps;
    
    
    for(Integer i=1;i<numAccts+1;i++) 
    {
        for (Integer j=1;j<numOppsPerAcct+1;j++) 
        {
        test_policy = new Policy__c(
                Name = 'Vex Test Policy/'+i+'/'+j,
                From_Opportunity__c = CustomerOpps[(i-1)+(j-1)].Id,
                Business_Type__c = 'NewBusiness',
                Issue_Date_Time__c = policy_start,
                Inception_Date_Time__c = policy_start,
                Expiry_Date_time__c = policy_start.addYears(1),
                OwnerId = UserInfo.getUserId(),
                Product__c = test_product.Id,
                Status__c = 'Live'
        );
    	If (PolicyRequired == True){
        	TestPolicies.add(test_policy);
    	}
        }
    }
    If (PolicyRequired == True){
        insert TestPolicies;
    }
    
}	// createVexData Method
}	// VexTestDataFactory Class